### ISSUE TITLE
What is the processing when there's network unstable issue?

### ISSUE THREAD

**Issue by wanga10000** [Leo4815162342/dukascopy-node#103]
Hi
I'm using CLI "npx dukascopy-node -i btcusd -from 2019-01-01 -to 2019-01-14 -t m1 -f json" to download the data.
I just wonder which option does the tool do when the network issue happens:
(1) Stop the downloading and return an error.
(2) Keep downloading data and there would be missing in the final downloaded json.
(3) The processing bar would stuck until the network get normal.
If (2) is the case, how do I "know" it happens with only npx running in command line without javascript (Node.js).
If (3) is the case (which I think it is), does it related to "retryCount" and "pauseBetweenRetriesMs" in the config object? 

My guess is (3) first, after hitting the "retryCount" and turn into (1). But I'm not sure.
How do I set it via CLI if I want to prevent from missing in the data?
Thanks.

**Comment by Leo4815162342** [comment]
Hi @wanga10000,
This is a very good question.

Here is how it's implemented currently:

If there is a network connection issue (we're not able to connect to dukascopy servers), the downloading would stop all together and error out.

If we are able to reach dukascopy servers, but they return non-ok responses for our requests (all except 200: 404, 503, etc) we treat it as an empty response without an error, so we proceed the downloading - the retry mechanism only works with this scenario.

In order to activate the retry mechanism via cli you should use `retries` and `retry-pause` parameters when using  `dukascopy-node`:

``` bash
npx dukascopy-node -i btcusd -from 2019-01-01 -to 2019-01-14 -t m1 -f json --retries 10 --retry-pause 1000
```

We can also enhance the retry mechanism and account for global network connection issues as well.
