### ISSUE TITLE
[BUG] The connection interrupts when downloading large dataset

### ISSUE THREAD

**Issue by Vasile-Peste** [Leo4815162342/dukascopy-node#146]
Hello,
I have a good and stable connection,
but when I download large tick datasets (for example 1yr) the connection interrupts randomly during the process

<img width="1444" alt="Screenshot 2023-06-25 at 20 46 00" src="https://github.com/Leo4815162342/dukascopy-node/assets/13590581/a8830f2a-6278-46d5-a536-521608ae9943">

Do you have any idea?

**Comment by Leo4815162342** [comment]
@Vasile-Peste
 
In case of downloading a large data set of ticks, I'd recommend adding `--cache`, `--retries`, `--retry-on-empty` and `--no-fail-after-retries` in order to make the download process as optimal as possible.

The command would look like this:

```bash
npx dukascopy-node -i xauusd -from 2016-01-01 -to 2017-01-01 -t tick -f csv --cache --retries 10 --retry-on-empty --no-fail-after-retries
```

Detailed info on caching: https://www.dukascopy-node.app/using-cache

Detailed info on retry mechanism: https://www.dukascopy-node.app/errors-and-empty-data
