### ISSUE TITLE
"Error in data stream" Error 

### ISSUE THREAD

**Issue by moremah** [Leo4815162342/dukascopy-node#60]
Hi,
Do you have any suggestion ?
data\npm>npx dukascopy-cli -i usdjpy -from 2022-04-13 -to 2022-04-14 -t m5 -f json
----------------------------------------------------
Downloading historical price data for:
----------------------------------------------------
Instrument:     usdjpy
Timeframe:      m5
From date:      2022-04-13T00:00:00.000Z
To date:        2022-04-13T13:38:13.127Z
Price type:     bid
Volumes:        false
UTC Offset:     0
Include flats:  false
Format:         json
----------------------------------------------------
|█████████████████████████████████████████████| 100%
Something went wrong:
 > "Error in data stream"

**Comment by Leo4815162342** [comment]
@moremah hey ;)
seems like the requested data was not available or empty on the time of your request. That can happen when you want to get the data for the current day, and since the dukascopy data is served in real time, it can cause an issue.

We've released an update that should help handling such issues better more gracefully. For that, please switch from `dukascopy-cli` to `dukascopy-node`(see https://github.com/Leo4815162342/dukascopy-node/discussions/62) and install the latest version of it.
