### ISSUE TITLE
add support for client side javascript

### ISSUE THREAD

**Issue by azataiot** [Leo4815162342/dukascopy-node#75]
```
datafeed.js:4 Uncaught ReferenceError: require is not defined
    at datafeed.js:4:32
```

When i tried to use dukascopy-node as a vanilla js module, i got this error.

I am using Vite.

**Comment by azataiot** [comment]
``` bash
✘ [ERROR] No matching export in "browser-external:path" for import "resolve"

    node_modules/dukascopy-node/dist/esm/chunk-S6VKB2J2.js:9753:9:
      9753 │ import { resolve } from "path";
```

**Comment by Leo4815162342** [comment]
@azataiot `dukascopy-node` can only be used in node.js runtime and will not work in browsers.

**Comment by azataiot** [comment]
is there any node specific code that currently dose not work on vanilla js? (which part of the process needs that part?)

**Comment by Leo4815162342** [comment]
@azataiot yes, we use nodejs file sytem API via `fs-extra` module for file [cache management](h[ttps://github.com/Leo4815162342/dukascopy-node/blob/master/src/cache-manager/index.ts](https://github.com/Leo4815162342/dukascopy-node/blob/master/src/cache-manager/index.ts#L3)) and for [CLI](https://github.com/Leo4815162342/dukascopy-node/blob/master/src/cli/index.ts#L5). Also we use `node-fetch` to [download](https://github.com/Leo4815162342/dukascopy-node/blob/master/src/buffer-fetcher/index.ts) binary artifacts from dukascopy servers.

On top of that, downloading dukascopy binary artifacts (e.g. https://datafeed.dukascopy.com/datafeed/EURCAD/2019/06/01/ASK_candles_min_1.bi5) directly form browser is not possible due to the CORS issues imposed by dukascopy servers.

What was you original use case? I assume you wanted a clientside application that allows downloading the data via `dukascopy-node` directly from the browser, is that correct?

**Comment by azataiot** [comment]
> 

yes, i was trying to connect `dukascopy-node` as a backend for TradingView's charting library. 

I am currently thinking to ways to solve the problem, either by replacing or updating some of the `dukascopy-node` functions or by wrapping the `dukascopy-node` with code to use as webhooks to get data.
